### PR TITLE
containerize backgroundremover

### PR DESCRIPTION
**Pull request by ravnoor**
I added a minimal `Dockerfile`, including a Github Actions CI/CD workflow to automatically build images.

Working version of the image: `docker pull ravnoor/backgroundremover:docker-latest`

### CODE REVIEW

**Comment by nadermx** [comment]
I still haven't spent much time if any reading up on docker.  Would you mind also adding something into the read me with this pull request? And then I will merge

**Comment by ravnoor** [comment]
> ### Installation using Docker
> ```bash
> git clone https://github.com/nadermx/backgroundremover.git
> cd backgroundremover
> docker build -t bgremover .
> alias backgroundremover='docker run -it --rm -v "$(pwd):/tmp" bgremover:latest'
> ```
---
This is the excerpt that I already added to the `README`. Of course, this requires basic knowledge of Docker. Is there something specific you'd like me to add?

**Comment by nadermx** [comment]
Thats fine.  Thank you. Will mege in a bit

**Comment by nadermx** [comment]
Github is saying the jobs have failed because it needs a user an login?

**Comment by ravnoor** [comment]
You repository didn't have access to my secrets - I have fixed it for now. You should be able to re-run the action (*Actions* > *containerize backgroundremover* > *Re-run all jobs*) without committing any new code.

Ideally, you would want to setup a Docker Hub account, and use your username (variable: `DOCKER_USERNAME`) and token as a password (`DOCKER_PASSWORD`) under *Settings* > *Secrets and variables* > *Actions*

Let me know if you need more help setting this up

**Pull request merged**
